# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.9.0

        environment:
          SKIP_PREFLIGHT_CHECK: "true"
          REACT_APP_WEBSITE_NAME: "OpenSRP-web"
          REACT_APP_DOMAIN_NAME: "http://localhost:3000"
          REACT_APP_OPENSRP_ACCESS_TOKEN_URL: "https://keycloak-stage.smartregister.org/auth/realms/reveal-stage/protocol/openid-connect/token"
          REACT_APP_OPENSRP_AUTHORIZATION_URL: "https://keycloak-stage.smartregister.org/auth/realms/reveal-stage/protocol/openid-connect/auth"
          REACT_APP_REACT_APP_OPENSRP_OAUTH_STATE: "opensrp"
          REACT_APP_OPENSRP_CLIENT_ID: "reveal-stage-server"
          REACT_APP_ENABLE_OPENSRP_OAUTH: "true"
          REACT_APP_OPENSRP_API_BASE_URL: "https://reveal-stage.smartregister.org/opensrp/rest/"
          REACT_APP_OPENSRP_USER_URL: "https://reveal-stage.smartregister.org/opensrp/user-details"
          REACT_APP_DISABLE_LOGIN_PROTECTION: "false"

    working_directory: ~/web

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      # TODO - why does the test fail without this.
      - run:
          name: build packages
          command: yarn lerna:prepublish

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run ts linter
          command: yarn lint

      - run:
          name: Run snap linter
          command: yarn lint-snap --debug

      - run:
          name: Run test with coverage
          command: yarn test --verbose --collectCoverage=true --forceExit --detectOpenHandles

      - run:
          name: upload coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

  test-docker-build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker buildx version
      - run: docker buildx create --use
      - run: docker buildx inspect --bootstrap
      - run: docker buildx build --platform linux/arm64,linux/amd64 --tag opensrp/web .

workflows:
  build:
    jobs:
      - test-docker-build
